name: Test App

on:
  push:
    branches: 
      - main
    paths:
      - ".github/workflows/**"
      - "app/**"
      - "test/**"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11"]

    name: Setup on ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Modify variables for testing
      shell: bash
      run: |
        # Replace the use of .env file with GitHub Secrets
        sed -i 's/api_key=api_key//g' 'app/core/translation.py'

    - name: Install Simple Comic Translator
      shell: bash
      run: |
        # Check Python version
        python --version

        # Create virtual environment
        python -m venv venv

        # Activate it
        source venv/bin/activate

        # Install dependencies
        pip install -r requirements-lock.txt

    - name: Run Simple Comic Translator
      shell: bash
      run: |
        # Run the app
        python main.py --input "test/remote/manhwa/RAW"