name: Test App

on:
  push:
    branches: 
      - main
    paths:
      - ".github/actions/**"
      - ".github/workflows/**"
      - "app/**"
      - "test/**"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ["3.11"]

    name: Setup on ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Setup Windows
      if: matrix.os == 'windows-latest'
      uses: ./.github/actions/windows
      with:
        env: ${{ env.GEMINI_API_KEY }}

    - name: Setup Linux
      if: matrix.os == 'ubuntu-latest'
      uses: ./.github/actions/linux
      with:
        env: ${{ env.GEMINI_API_KEY }}

    - name: Setup macOS
      if: matrix.os == 'macos-latest'
      uses: ./.github/actions/macos
      with:
        env: ${{ env.GEMINI_API_KEY }}